name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    name: Build & Test
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Show Swift version
        run: swift --version

      - name: Build
        run: swift build

      - name: Test
        run: swift test

  lint:
    name: swift-format lint
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install swift-format
        run: brew install swift-format

      - name: Lint
        run: swift-format lint -r -s Sources decoders Tests
